services:
    chatsync_db:
        image: mysql:latest
        container_name: chatsync_database
        ports:
            - 3306:3306
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_USER=cs_user
            - MYSQL_PASSWORD=1234
            - MYSQL_DATABASE=chatsync