USE chatsync;

CREATE TABLE IF NOT EXISTS `messages` (
	`id` INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	`author` VARCHAR(255) NOT NULL,
	`avatar` VARCHAR(255) NOT NULL,
	`message` LONGTEXT NOT NULL,
	`date` DATETIME NOT NULL
)CHARSET=UTF8MB4, ENGINE=InnoDB;